#! /usr/bin/env python3

"""
---------------------------------------------------------------------------------------------
# File    : fgen
# Author  : Neo.H
# Date    : Sep 19, 2018
# Version : v1.00
---------------------------------------------------------------------------------------------
A sub command to generate the file list for both simulation and debug.
For simulation , there should be the specified compile.lis
---------------------------------------------------------------------------------------------
inputs:
	-eda <edatool>, specify the eda tool, for now, valid only for VCS tool, and interfaces will
be sustained for other eda tools, mainly for xcelium.
	-help, help option to display all valid options for fgen tool.
	-rtl <rtl_type>, specify the rtl type to lead the tool to generate the different combination
of compile.lis. Default rtl_type is 'asic'.
	-path <dest_path>, specify the path to generate the filelist, this is an optional param, if
not specified, the default path: <proj_home>/out/sim/<rtl_type>/tests/ will be used.
	-proj_home <path>, the project home specified by caller.
	-erf <file_name>, external rtl file, this means the file should be added to rtl.lis, with
different rtl mode, the erf can specify corresponding rtl modules.
	-y <libraries>, to specify the library path, by different eda tools, this option will be
translated to the corresponding options recognized by the tool. Besides, this option only
support the eda tool that can support filelist option insertion.
	-libext <extensions>, this option work together with -y option, to specify the searching
file with specified extension. This option can be input with multiple times for specifying
multiple extensions.
	-target <target name>, the option specify the destined usage for calling this tool. the
target name for now are valid within:
		-- sim: for simulation, in this target, the compile.lis, rtl.lis, dpi.lis, fsim.lis and
sim_model.lis will be generated nomatter files above exists or not.
		-- wav: for wave vision, in this target, wave.lis, rtl.lis, fsim.lis and sim_model.lis will
be generated nomatter files above exists or not.
	-pt <proj_type>: the project type option, valid only within IP and SOC.
---------------------------------------------------------------------------------------------
outputs, for different target, different list will be generated.
	sim:
		-- <o_path>/compile.lis
		-- <o_path>/rtl.lis: storing all RTL files.
		-- <o_path>/dpi.lis: list of dpi.
		-- <o_path>/fsim.lis: storing all verification files for functional simulation.
		-- <o_path>/sim_model.lis: storing all simulation modules that act the behavior for some
RTL modules.
	wav:
		-- <o_path>/verdi.lis, a list for verdi tool.
		-- <o_path>/rtl.lis: storing all RTL files.
		-- <o_path>/fsim.lis: storing all verification files for functional simulation.
		-- <o_path>/sim_model.lis: storing all simulation modules that act the behavior for some
RTL modules.
---------------------------------------------------------------------------------------------
exit SIGs:
	-- 0, a normal exit
---------------------------------------------------------------------------------------------
generating considerations:
	-- common dir will be included as +incdir+<commons>
---------------------------------------------------------------------------------------------
	-- compile.lis: the list for eda tools, which constains the rtl.lis, verif_fsim.lis and
sim_model.lis.
---------------------------------------------------------------------------------------------

"""
from pcfg import fgen_cfg;
from options import options;

cfg = fgen_cfg();

proj_home = '';

o_path = '';

## }
