#! /usr/bin/env python3
"""
The run shell for the whole tool, which is a user accessible command used to call all other sub commands.
---------------------------------------------------------------------------------------------------------
Sub commands this tool supports:
	-- env build up: build
	-- filelist generating: fgen
	-- compile: comp
	-- simulation: sim
	-- wave vision operation: wave
	-- coverage operation: cov
	--
---------------------------------------------------------------------------------------------------------
The interfaces we should defined here:



"""


## -- Global Vars ---------------------------------------------------------------------------------------
## this block will define all global variables that may be used in the whole module, or other external
## code.
## ------------------------------------------------------------------------------------------------------


## ------------------------------------------------------------------------------------------------------
