#! /usr/bin/env python3

"""
---------------------------------------------------------------------------------------------
# File    : report
# Author  : Neo.H
# Date    : Sep 19, 2018
# Version : v1.00
---------------------------------------------------------------------------------------------
This module encapsulates all report APIs for run tool.
---------------------------------------------------------------------------------------------
"""

class rpt: ##{

	def __init__(self): ## {
	## }

	def fatal(self,msg): ## {
		print ("[\033[32;0mFATAL\033[0m] "+msg);
	## }

	def error(self,msg): ## {
		print ("[\033[32;0mERROR\033[0m] "+msg);
	## }

## }
